# Generated by Django 2.2.3 on 2019-07-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default='', max_length=15)),
                ('cash', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
