# Generated by Django 2.2.3 on 2019-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(default='', max_length=50)),
                ('sector', models.CharField(default='', max_length=15)),
                ('row', models.CharField(default='', max_length=15)),
                ('place', models.CharField(default='', max_length=15)),
                ('user', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
