# Generated by Django 2.2.3 on 2019-07-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockPlaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockplaces',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
