# Generated by Django 2.2.3 on 2019-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=50)),
                ('origin_name', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=4)),
                ('coutry', models.CharField(default='', max_length=15)),
                ('description', models.CharField(default='', max_length=600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
